---
- name: Base System Setup
  hosts: localhost
  connection: local
  become: true
  gather_facts: yes

  tasks:
    - name: Update package cache
      package:
        update_cache: yes
      when: ansible_os_family in ['Debian', 'RedHat']

    - name: Install base utility packages
      package:
        name:
          - curl
          - wget
          - zsh
          - git
          - tree
          - gawk
        state: present

    - name: Install development packages
      package:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
        state: present

    - name: Create python symlink
      file:
        src: "/usr/bin/python3"
        dest: "/usr/bin/python"
        state: link
      when: not ansible_check_mode

    - name: Create pip symlink
      file:
        src: "/usr/bin/pip3"
        dest: "/usr/bin/pip"
        state: link
      when: not ansible_check_mode

